In [1]:
import numpy as np

In [2]:
v = np.random.seed(42)


In [5]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [6]:
stepFunction(0)

1

In [7]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [16]:
W = np.array(np.random.rand(2,1))

In [17]:
W

array([[ 0.96563203],
       [ 0.80839735]])

In [23]:
b = np.random.rand(1)[0]

In [24]:
b

0.4401524937396013

In [25]:
x = np.array([1,2,3,4])

In [26]:
x

array([1, 2, 3, 4])

In [29]:
for element in x:
    print(element)

1
2
3
4


In [30]:
len(x)

4

In [31]:
for i in range(len(x)):
    print(x[i])

1
2
3
4


In [32]:
if 1 == 1:
    print("hello")

hello


In [20]:
import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [27]:
sigmoid(2)

0.8807970779778823

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Some helper functions for plotting and drawing lines

def plot_points(X, y):
    admitted = X[np.argwhere(y==1)]
    rejected = X[np.argwhere(y==0)]
    plt.scatter([s[0][0] for s in rejected], [s[0][1] for s in rejected], s = 25, color = 'blue', edgecolor = 'k')
    plt.scatter([s[0][0] for s in admitted], [s[0][1] for s in admitted], s = 25, color = 'red', edgecolor = 'k')

def display(m, b, color='g--'):
    plt.xlim(-0.05,1.05)
    plt.ylim(-0.05,1.05)
    x = np.arange(-10, 10, 0.1)
    plt.plot(x, m*x+b, color)

In [7]:
weights = np.random.normal(scale=1 / 2**.5, size=2)

In [8]:
weights

array([ 0.90286066,  0.84765517])

In [9]:
bias = 0

In [10]:
weights.shape

(2,)

In [11]:
del_w = np.zeros(weights.shape)

In [12]:
del_w


array([ 0.,  0.])

In [13]:
X = np.array([0, 0.5, 1])

In [14]:
y = np.array([0)

In [18]:
plot_points([1,2],[1,2])

TypeError: only integer scalar arrays can be converted to a scalar index

In [19]:
sigmoid(2)

NameError: name 'sigmoid' is not defined

In [29]:
print('hello')

hello


In [30]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [31]:
def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [32]:
x = np.array([0.1, 0.3])

In [33]:
x

array([ 0.1,  0.3])

In [34]:
y = 0.2

In [35]:
weights = np.array([-0.8, 0.5])

In [36]:
weights

array([-0.8,  0.5])

In [37]:
learnrate = 0.5

In [38]:
h = x[0] * weights[0] + x[1] * weights[1]

In [39]:
h

0.069999999999999979

In [41]:
nn_output = sigmoid(h)
nn_output

0.51749285766638975

In [43]:
error = y - nn_output
error

-0.31749285766638974

In [45]:
output_grad = sigmoid_prime(h)
output_grad

0.24969399993066344

In [46]:
error_term = error * output_grad
error_term

-0.079276061580137655

In [51]:
del_w = [ learnrate * error_term * x[0],
          learnrate * error_term * x[1]]

In [52]:
del_w

[-0.0039638030790068828, -0.011891409237020648]

In [53]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consilated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.matmul(x, w)

# TODO: Calculate output of neural network
nn_output = sigmoid(h)

# TODO: Calculate error of neural network
error = y - nn_output

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error * sigmoid_prime(h)

# TODO: Calculate change in weights
del_w = learnrate * error_term * x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

Neural Network output:
0.689974481128
Amount of Error:
-0.189974481128
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]


In [58]:
weights = np.random.normal(scale=1/5**.5, size=3)
weights

array([-0.23569273,  0.05359669, -0.24460447])

# This code is available in section 2 lesson 2 bullet 5

This code will not work below, because we don't have access to the csv ;) 

In [62]:
import numpy as np
from data_prep import features, targets, features_test, targets_test


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

# TODO: We haven't provided the sigmoid_prime function like we did in
#       the previous lesson to encourage you to come up with a more
#       efficient solution. If you need a hint, check out the comments
#       in solution.py from the previous lecture.


# Use to same seed to make debugging easier
np.random.seed(42)

n_records, n_features = features.shape
last_loss = None

# Initialize weights
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

# Neural Network hyperparameters
epochs = 1000
learnrate = 0.5

for e in range(epochs):
    del_w = np.zeros(weights.shape)
    for x, y in zip(features.values, targets):
        # Loop through all records, x is the input, y is the target

        # Note: We haven't included the h variable from the previous
        #       lesson. You can add it if you want, or you can calculate
        #       the h together with the output

        # TODO: Calculate the output
        output = sigmoid(np.matmul(x, weights))

        # TODO: Calculate the error
        error = y - output

        # TODO: Calculate the error term
        # the sigmoid prime is sigmoid * 1-sigmoid. 
        # Since we calculated the sigmoid as an output variable
        # we use this practical formula below: 
        error_term = error * output * (1-output)

        # TODO: Calculate the change in weights for this sample
        #       and add it to the total weight change
        del_w += learnrate * error_term * x

    # TODO: Update weights using the learning rate and the average change in weights
    weights += del_w / n_records

    # Printing out the mean square error on the training set
    if e % (epochs / 10) == 0:
        out = sigmoid(np.dot(features, weights))
        loss = np.mean((out - targets) ** 2)
        if last_loss and last_loss < loss:
            print("Train loss: ", loss, "  WARNING - Loss Increasing")
        else:
            print("Train loss: ", loss)
        last_loss = loss


# Calculate accuracy on test data
tes_out = sigmoid(np.dot(features_test, weights))
predictions = tes_out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))

ModuleNotFoundError: No module named 'data_prep'

In [66]:
# Network size
N_input = 4
N_hidden = 3
N_output = 2

In [67]:
np.random.seed(42)

In [68]:
X = np.random.randn(4)

In [69]:
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [70]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))

In [71]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [72]:
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [73]:
hidden_layer_in = np.dot(X, weights_input_to_hidden)

In [74]:
hidden_layer_in

array([-0.34365494, -0.29801368,  0.00097362])

In [75]:
hidden_layer_out = sigmoid(hidden_layer_in)

In [76]:
hidden_layer_out

array([ 0.41492192,  0.42604313,  0.5002434 ])

In [77]:
output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)

In [78]:
sigmoid(output_layer_in)

array([ 0.49815196,  0.48539772])

In [79]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[ 0.41492192  0.42604313  0.5002434 ]
Output-layer Output:
[ 0.49815196  0.48539772]


In [80]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

In [83]:
hidden_layer_input = np.dot(x, weights_input_hidden)

In [84]:
hidden_layer_output = sigmoid(hidden_layer_input)

In [85]:
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)

In [86]:
output = sigmoid(output_layer_in)

In [87]:
output

0.48497343084992534

In [88]:
error = target - output

In [89]:
output_error_term = error * output * (1 - output)

In [90]:
hidden_error_term = weights_hidden_output * output_error_term * hidden_layer_output * (1 - hidden_layer_output)

In [91]:
hidden_error_term

array([ 0.00070802, -0.00204471])

In [92]:
x

array([ 0.5,  0.1, -0.2])

In [93]:
learnrate

0.5

In [94]:
hidden_error_term

array([ 0.00070802, -0.00204471])

In [96]:
x.shape

(3,)

In [97]:
hidden_error_term.shape

(2,)

In [98]:
x[:, None]

array([[ 0.5],
       [ 0.1],
       [-0.2]])

In [100]:
hidden_error_term * x[:, None]

array([[  3.54011093e-04,  -1.02235701e-03],
       [  7.08022187e-05,  -2.04471402e-04],
       [ -1.41604437e-04,   4.08942805e-04]])

In [101]:
x_t = x[:, None]

In [102]:
x_t.shape

(3, 1)

In [103]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)

# TODO: Calculate error term for hidden layer
hidden_error_term = weights_hidden_output * output_error_term * hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


Change in weights for hidden layer to output layer:
[ 0.00804047  0.00555918]
Change in weights for input layer to hidden layer:
[[  1.77005547e-04  -5.11178506e-04]
 [  3.54011093e-05  -1.02235701e-04]
 [ -7.08022187e-05   2.04471402e-04]]


In [104]:
sigmoid(2)

0.88079707797788231

In [105]:
sigmoid(20)

0.99999999793884631

In [106]:
sigmoid(-2)

0.11920292202211755

In [107]:
sigmoid(-20)

2.0611536181902037e-09